version: '3.8'

services:
  app:
    build: .
    container_name: compose-app-java
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - mongo-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/minhadb
      - SPRING_DATASOURCE_USERNAME=meuuser
      - SPRING_DATASOURCE_PASSWORD=minhasenha
      - SPRING_DATA_MONGODB_URI=mongodb://meuuser:minhasenha@mongo-db:27017/minhadb?authSource=admin

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=meuuser
      - POSTGRES_PASSWORD=minhasenha
      - POSTGRES_DB=minhadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo-db:
    image: mongo:7
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=meuuser
      - MONGO_INITDB_ROOT_PASSWORD=minhasenha
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongo_data:
